FROM postgres:14-alpine

#COPY ./init-scripts /scripts/init-scripts
#COPY ./utils /scripts/utils
#
#COPY ./init.sh /docker-entrypoint-initdb.d/init.sh
#
#RUN chmod +x /docker-entrypoint-initdb.d/init.sh