// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpookyTattoos.Infrastructure.Persistence;

#nullable disable

namespace SpookyTattoos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SpookyTattoosDbContext))]
    [Migration("20260716113740_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_admins");

                    b.HasIndex("Active")
                        .HasDatabaseName("ix_admins_active");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_admins_email");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Email"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Email"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Username")
                        .HasDatabaseName("ix_admins_username");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Username"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Username"), new[] { "gin_trgm_ops" });

                    b.ToTable("admins", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@spookytattoos.com",
                            LastLogin = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Password = "Admin123!",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<int>("GhostPoints")
                        .HasColumnType("integer")
                        .HasColumnName("ghost_points");

                    b.Property<string>("InstagramUser")
                        .HasColumnType("text")
                        .HasColumnName("instagram_user");

                    b.Property<DateTimeOffset?>("LastJob")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_job");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("Active")
                        .HasDatabaseName("ix_clients_active");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_clients_email");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Email"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Email"), new[] { "gin_trgm_ops" });

                    b.HasIndex("FullName")
                        .HasDatabaseName("ix_clients_full_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FullName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("FullName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("GhostPoints")
                        .IsDescending()
                        .HasDatabaseName("ix_clients_ghost_points");

                    b.HasIndex("InstagramUser")
                        .HasDatabaseName("ix_clients_instagram_user");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("InstagramUser"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("InstagramUser"), new[] { "gin_trgm_ops" });

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<int>("PromoId")
                        .HasColumnType("integer")
                        .HasColumnName("promo_id");

                    b.HasKey("Id")
                        .HasName("pk_coupons");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_coupons_client_id");

                    b.HasIndex("PromoId")
                        .HasDatabaseName("ix_coupons_promo_id");

                    b.ToTable("coupons", (string)null);
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_name");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("EventName")
                        .HasDatabaseName("ix_events_event_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("EventName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("EventName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_events_start_date");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("CK_Event_Dates", "end_date >= start_date");
                        });
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("final_price");

                    b.Property<string>("ReferenceImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_image_url");

                    b.Property<DateTimeOffset>("ScheduledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_jobs_client_id");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Piercing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyPart")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_part");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_job_piercing_details");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_piercing_details_job_id");

                    b.ToTable("job_piercing_details", (string)null);
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("PostText")
                        .HasColumnType("text")
                        .HasColumnName("post_text");

                    b.HasKey("Id")
                        .HasName("pk_post_catalog_items");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_post_catalog_items_created_at");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_post_catalog_items_job_id");

                    b.ToTable("post_catalog_items", (string)null);
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.PostImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.HasKey("Id")
                        .HasName("pk_post_final_images");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_final_images_post_id");

                    b.ToTable("post_final_images", (string)null);
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Promo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conditions");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("GhostPoints")
                        .HasColumnType("integer")
                        .HasColumnName("ghost_points");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_promos");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("ix_promos_end_date");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_promos_start_date");

                    b.ToTable("promos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Promo_Dates", "end_date >= start_date");
                        });
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Tattoo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BodyZoneScore")
                        .HasColumnType("integer")
                        .HasColumnName("body_zone");

                    b.Property<int>("DetailScore")
                        .HasColumnType("integer")
                        .HasColumnName("detail");

                    b.Property<int>("FillScore")
                        .HasColumnType("integer")
                        .HasColumnName("fill");

                    b.Property<decimal>("FinalTattooPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("final_tattoo_price");

                    b.Property<bool>("HasColor")
                        .HasColumnType("boolean")
                        .HasColumnName("has_color");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<int>("ShadowScore")
                        .HasColumnType("integer")
                        .HasColumnName("shadow");

                    b.Property<decimal>("SizeCm")
                        .HasColumnType("numeric")
                        .HasColumnName("size_cm");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("style");

                    b.Property<string>("name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_job_tattoo_details");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_tattoo_details_job_id");

                    b.ToTable("job_tattoo_details", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tattoo_BodyZoneScore", "\"body_zone\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_Tattoo_DetailScore", "\"detail\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_Tattoo_FillScore", "\"fill\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_Tattoo_ShadowScore", "\"shadow\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmitterId")
                        .HasColumnType("integer")
                        .HasColumnName("emitter_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_vouchers");

                    b.HasIndex("EmitterId")
                        .HasDatabaseName("ix_vouchers_emitter_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_vouchers_expires_at");

                    b.HasIndex("IsUsed")
                        .HasDatabaseName("ix_vouchers_is_used");

                    b.ToTable("vouchers", (string)null);
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Coupon", b =>
                {
                    b.HasOne("SpookyTattoos.Domain.Entities.Client", "Client")
                        .WithMany("Coupons")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coupons_clients_client_id");

                    b.HasOne("SpookyTattoos.Domain.Entities.Promo", "Promo")
                        .WithMany()
                        .HasForeignKey("PromoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coupons_promos_promo_id");

                    b.Navigation("Client");

                    b.Navigation("Promo");
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Job", b =>
                {
                    b.HasOne("SpookyTattoos.Domain.Entities.Client", "Client")
                        .WithMany("Jobs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_clients_client_id");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Piercing", b =>
                {
                    b.HasOne("SpookyTattoos.Domain.Entities.Job", "Job")
                        .WithMany("Piercings")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_piercing_details_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Post", b =>
                {
                    b.HasOne("SpookyTattoos.Domain.Entities.Job", "Job")
                        .WithOne("CatalogPost")
                        .HasForeignKey("SpookyTattoos.Domain.Entities.Post", "JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_catalog_items_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.PostImage", b =>
                {
                    b.HasOne("SpookyTattoos.Domain.Entities.Post", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_final_images_post_catalog_items_post_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Tattoo", b =>
                {
                    b.HasOne("SpookyTattoos.Domain.Entities.Job", "Job")
                        .WithMany("Tattoos")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_tattoo_details_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Voucher", b =>
                {
                    b.HasOne("SpookyTattoos.Domain.Entities.Client", "Emitter")
                        .WithMany("IssuedVouchers")
                        .HasForeignKey("EmitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vouchers_clients_emitter_id");

                    b.Navigation("Emitter");
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Client", b =>
                {
                    b.Navigation("Coupons");

                    b.Navigation("IssuedVouchers");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Job", b =>
                {
                    b.Navigation("CatalogPost");

                    b.Navigation("Piercings");

                    b.Navigation("Tattoos");
                });

            modelBuilder.Entity("SpookyTattoos.Domain.Entities.Post", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
